config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',    :to => 'sessions#destroy'
  

end

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  est un projet de livre et de screencasts pour apprendre le développement web
  avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. C'est l'Application Exemple de ce tutoriel.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact du Tutoriel Ruby on Rails à propos de l'Application Exemple à la
  <a href="http://railstutorial.org/feedback">page de feedback</a>.
</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails Tutorial sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette application exemple, consultez le
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
   <table class="front" summary="Pour visiteur identifié"> 
     <tr>
         <td class="main">
            <h1 class="micropost">Quoi de neuf ?</h1>
            <%= render 'shared/micropost_form' %>
            <%= render 'shared/feed' %>
        </td>
        <td class="sidebar round">
            <%= render 'shared/user_info' %>
            <%= render 'shared/stats' %>
        </td>
      </tr>
    </table> 
   </table>
<% else %>
    <h1>Sample App</h1>
    <p>
      C'est la page d'accueil de l'Application Exemple du
      <a href="http://railstutorial.org/">Tutoriel Ruby on Rails</a>.
    </p>

    <%= link_to "S'inscrire !", signup_path, :class => "signup_button round" %>
<% end %>